### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by iGetUploaded** [miltinhoc/Discord-Nuker#2]
Do you have to build this? or is there supposed to be an exe?

**Comment by miltinhoc** [comment]
Yes, but should be pretty straight forward

**Comment by miltinhoc** [comment]
If you have visual studio, you can restore the nuget packages and just build it

**Comment by iGetUploaded** [comment]
I built it and it made the application but when I try running it it doesn't even open not sure what i'm doing wrong 🤔

Here's a video clip

https://user-images.githubusercontent.com/54633753/155821176-96ff79bd-b78e-473a-bac5-2ab675ee5bcf.mp4

**Comment by miltinhoc** [comment]
If you run it from inside visual studio does it show any error on the console window?

**Comment by miltinhoc** [comment]
and please check if configs.json was created, if so update the token, etc

**Comment by iGetUploaded** [comment]
When I try to run through Visual Studio I get this 

![image](https://user-images.githubusercontent.com/54633753/155855689-ab361f38-8abc-44e0-9a7a-ec4adf8f63f4.png)

**Comment by miltinhoc** [comment]
ah ok, then makes sense ahah could you try install the version 3.1.0 and try again, please?

**Comment by iGetUploaded** [comment]
Got it to work now thanks : )
