### ISSUE TITLE
It doesn't shows the guild and doesn't detect it while nuking

### ISSUE THREAD

**Issue by jannysssx** [miltinhoc/Discord-Nuker#3]
It doesn't shows the guild and doesn't detect it while nuking

**Comment by miltinhoc** [comment]
Hi, can you be more specific, please? did you update the config.json with the bot token?

**Comment by miltinhoc** [comment]
I Think I see the problem, will try and push a fix! thanks

**Comment by jannysssx** [comment]
> Hi, can you be more specific, please? did you update the config.json with the bot token?

yes, i did

**Comment by jannysssx** [comment]
> I Think I see the problem, will try and push a fix! thanks

can you tell me what the problem is?

**Comment by jannysssx** [comment]
@miltinhoc have you fixed it?

**Comment by miltinhoc** [comment]
not yet, might be dependencies, Im checking it

**Comment by miltinhoc** [comment]
I updated references, can you try now? clone, restore nuget packets, build and then update token on the configs.json

**Comment by jannysssx** [comment]
okay, it works now, thank you :3
